name: Update hashes
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '15 2 * * *' # runs daily at 2:15

jobs:
  update-hashes:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Nix
        uses: cachix/install-nix-action@v17
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Set environment variables
        shell: bash
        run: |
          echo "GIT_AUTHOR_NAME=github-actions[bot]" >> $GITHUB_ENV
          echo "GIT_AUTHOR_EMAIL=<github-actions[bot]@users.noreply.github.com>" >> $GITHUB_ENV
          echo "GIT_COMMITTER_NAME=github-actions[bot]" >> $GITHUB_ENV
          echo "GIT_COMMITTER_EMAIL=<github-actions[bot]@users.noreply.github.com>" >> $GITHUB_ENV
      - name: Update all hashes
        shell: bash
        run: |
          git rm hashes/*.nix
          nix run .#generate-all-hashes
          git add hashes/*.nix
          git commit -m "hashes: update"
      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: update-hashes
          delete-branch: true
          title: "Update OpenWrt download hashes"
          token: ${{ secrets.GITHUB_TOKEN }}
          labels: update
          commit-message: |
            Regular update of OpenWrt release hashes

            https://github.com/astro/nix-openwrt-imagebuilder/actions/workflows/update-hashes.yml
